class GradeUtils {
  static const List<String> grades = [
    'PSA 1',
    'PSA 2',
    'PSA 3',
    'PSA 4',
    'PSA 5',
    'PSA 6',
    'PSA 7',
    'PSA 8',
    'PSA 9',
    'PSA 10',
    'BGS 1',
    'BGS 2',
    'BGS 3',
    'BGS 4',
    'BGS 5',
    'BGS 6',
    'BGS 7',
    'BGS 8',
    'BGS 9',
    'BGS 9.5',
    'BGS 10',
    'BGS 黑10',
    'CGC 1',
    'CGC 2',
    'CGC 3',
    'CGC 4',
    'CGC 5',
    'CGC 6',
    'CGC 7',
    'CGC 8',
    'CGC 9',
    'CGC 10',
    'CGC 金10',
    'CCIC 1',
    'CCIC 2',
    'CCIC 3',
    'CCIC 4',
    'CCIC 5',
    'CCIC 6',
    'CCIC 7',
    'CCIC 8',
    'CCIC 9',
    'CCIC 9.5',
    'CCIC 银10',
    'CCIC 金10',
  ];

  static bool isValidGrade(String grade) {
    return grades.contains(grade);
  }
}
